name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # make sure build/ci work properly
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
